name             'dubya'
maintainer       'Tom Scott'
maintainer_email 'tubbo@psychedeli.ca'
license          'All rights reserved'
description      'An HTML static site generator for vimwiki'
long_description 'An HTML static site generator for vimwiki'
version          '0.0.1'

depends 'nginx'
depends 'ruby-install'
